# Generated by Django 4.2.4 on 2023-08-23 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.IntegerField()),
                ('game_description', models.CharField(max_length=500)),
                ('date_of_release', models.DateTimeField()),
                ('image', models.ImageField(upload_to='images/')),
                ('category', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='SystemRequirements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_system', models.CharField(max_length=30)),
                ('CPU', models.CharField(max_length=20)),
                ('RAM', models.CharField(max_length=10)),
                ('video_card', models.CharField(max_length=20)),
                ('free_space', models.CharField(max_length=25)),
                ('game', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop_app.game')),
            ],
        ),
    ]
