# Generated by Django 4.2.4 on 2023-08-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.URLField()),
                ('title', models.CharField(max_length=255)),
                ('price', models.PositiveIntegerField()),
                ('date_of_release', models.DateField()),
                ('game_description', models.TextField()),
                ('date_updated', models.CharField(max_length=4)),
                ('genre', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('edition_type', models.CharField(max_length=50)),
                ('interface_language', models.CharField(max_length=50)),
                ('voice_language', models.CharField(max_length=50)),
                ('copy_protection', models.CharField(max_length=50)),
                ('os_requirements', models.TextField()),
                ('processor_requirements', models.CharField(max_length=255)),
                ('memory_requirements', models.CharField(max_length=255)),
                ('graphics_card_requirements', models.CharField(max_length=255)),
                ('disk_space_requirements', models.CharField(max_length=255)),
            ],
        ),
    ]
