# Generated by Django 4.2.4 on 2023-08-28 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='copy_protection',
        ),
        migrations.RemoveField(
            model_name='game',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='game',
            name='edition_type',
        ),
        migrations.RemoveField(
            model_name='game',
            name='interface_language',
        ),
        migrations.RemoveField(
            model_name='game',
            name='publisher',
        ),
        migrations.RemoveField(
            model_name='game',
            name='voice_language',
        ),
    ]
