# Generated by Django 4.2.4 on 2023-08-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0002_remove_game_copy_protection_remove_game_developer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='img',
        ),
        migrations.AddField(
            model_name='game',
            name='path',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
    ]
