# Generated by Django 4.2.4 on 2023-08-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0003_remove_game_img_game_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='platform',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
