# Generated by Django 4.2.4 on 2023-08-29 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0005_alter_game_date_of_release_alter_game_date_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
